site_name: KevinGuo Blog
site_description: KevinGuo的个人网站
site_author: KevinGuo
site_url: https://kevinguo1007.github.io/
copyright: 郭越齐 CC-BY-4.0
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/KevinGuo1007/KevinGuo1007.github.io
repo_name: KevinGuo1007.github.io
# [bottom-left corner]
# [版权说明]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice

theme:
  favicon: image/k.svg
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: teal
    accent: teal
    # # 夜间模式
    # - scheme: slate
    #   primary: teal
    #   accent: teal
    #   toggle:
    #     icon: material/weather-sunny
    #     name: 切换至浅色模式
    # # 日间模式
    # - scheme: default
    #   primary: cyan
    #   accent: cyan
    #   toggle:
    #     icon: material/weather-night
    #     name: 切换至深色模式

  features:
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

  language: zh # 一些提示性的文字会变成中文
  icon:
    logo: simple/known
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github

nav:
  - 关于我:
      - aboutMe/index.md
      - 个人介绍: aboutMe/introduction.md
      - 个人经历: aboutMe/experience.md
  - 博客:
      - blog/index.md
      - blog/ARecommendationaboutchoosingLaptopforComputerScienceFreshmen.md
      - blog/MissingSemester.md
      - blog/computerdesk.md
      - blog/LaTexStudy.md
  - 作品:
      - work/index.md
      - 影视创作:
          - work/MediaProduction/mediawork-1.md
          - work/MediaProduction/mediawork-2.md
          - work/MediaProduction/mediawork-3.md
      - 编程项目:
          - work/CodeProduction/spiders-for-weather.md
  - 研究:
      - reserch/index.md
  - 随笔:
      - diaries/index.md
      - diaries/diary-1.md
      - diaries/HuaweiPatriotism.md

# [bottom-right corner]
extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | KevinGuo1007
      icon: fontawesome/brands/github
      link: https://github.com/KevinGuo1007
    - name: Bilibili | 觅森馨
      icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/39395433
    - name: 小红书 | 觅森馨
      icon: material/book-open-variant
      link: https://www.xiaohongshu.com/user/profile/5e174618000000000100b2ef?xhsshare=CopyLink&appuid=5e174618000000000100b2ef&apptime=1732549562&share_id=0ffbf49236774b2a9fb09ea5208dceb0

  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

# [Extensions]
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags
markdown_extensions:
  # [代码高亮]
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  # [数学公式支持]
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持] 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小，添加 `{ align=left } `设置图片对齐
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  # [警告]
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  - footnotes
  # [给标题添加链接]
  - toc:
      permalink: true
      title: Table of Contents
  # [添加数据表]
  - tables
  # [添加图标及表情符号]
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # [列表]


  - def_list
  - pymdownx.tasklist:
      custom_checkbox:
        true
        # # [数学公式支持]
        # # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
        # - pymdownx.arithmatex:
        #     generic: true
        # # [图片功能支持]
        # # https://squidfunk.github.io/mkdocs-material/reference/images/
        # # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
        # - attr_list
        # - md_in_html
        # # [给标题添加链接]
        # # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
        # - toc:
        #     permalink: true # 固定标题位置为当前位置
        # # [代码语法高亮]
        # # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
        # # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
        # - pymdownx.highlight:
        #     # 显示行号
        #     linenums: true
        #     # 显示编程语言名称
        #     auto_title: true
        #     # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
        #     line_spans: __span
        #     # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
        #     pygments_lang_class: true
        # - pymdownx.inlinehilite
        # - pymdownx.snippets
        # - pymdownx.superfences
        # # [Markdown 提示]
        # # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
        # - admonition
        # - pymdownx.details

extra_javascript:
  # [Giscus评论功能]
  - https://giscus.app/client.js
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css
  # 自定义CSS样式
  - stylesheets/extra.css
